name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v2

      - name: Setup Swift version
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10.0"

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.4.app && /usr/bin/xcodebuild -version
      
      - name: Build package
        run: swift build

      - name: Runing tests package
        run: swift test
